apiVersion: v2
name: clinvar-ingest
description: Argo workflow for regular ingest of ClinVar archives.
version: 0.0.0
dependencies:
  - name: argo-controller
    version: 0.0.2
    repository: file:///charts/argo-controller
    alias: argo
